name: Install Zola

on:
  workflow_call:

# Due to some bug I can't use env in a reuisable job: https://github.com/actions/runner/issues/2372
# env:
#   ZOLA_VERSION: 0.20.0

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.20.0
