base_url = "https://github.com/janmasrovira/hermes"
theme = "hermes"
title = "ascetic slug"
description = "This is an example description"
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
repo_url = "https://github.com/janmasrovira/hermes/tree/main/content/"
katex_version = "0.16.22"

menu = [
    { name = "[blog]", url = "/blog", weight = 1 },
    { name = "[projects]", url = "/projects", weight = 2 },
]

socials = [
    { name = "mail", url = "mailto:janmasrovira@gmail.com", icon = "email" },
    { name = "github", url = "https://github.com/janmasrovira/", icon = "github" },
    { name = "gitlab", url = "https://gitlab.com/janmasrovira/", icon = "gitlab" },
    { name = "LinkedIn", url = "https://linkedin.com/in/jan-mas-rovira", icon = "linkedin" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false
