theme = "anemone"
base_url = "https://example.dev"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "one-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Jan Mas Rovira"
favicon = "favicon.ico"
list_pages = false
twitter_card = false
enable_search = true
header_nav = [
  { url = "/", name_en = "home/" },
  { url = "/blog", name_en = "blog/" },
  { url = "/project", name_en = "projects/" }
]
