name: Zola Build Check

on:
  pull_request:
  push:
    branches:
      - main
      - publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: ./.github/workflows/get-zola.yml

      - name: Run zola build
        run: zola build
